attribute @s[scores={fusedDmgA=20..}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 20 add
attribute @s[scores={fusedDmgA=19}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 19 add
attribute @s[scores={fusedDmgA=18}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 18 add
attribute @s[scores={fusedDmgA=17}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 17 add
attribute @s[scores={fusedDmgA=16}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 16 add
attribute @s[scores={fusedDmgA=15}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 15 add
attribute @s[scores={fusedDmgA=14}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 14 add
attribute @s[scores={fusedDmgA=13}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 13 add
attribute @s[scores={fusedDmgA=12}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 12 add
attribute @s[scores={fusedDmgA=11}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 11 add
attribute @s[scores={fusedDmgA=10}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 10 add
attribute @s[scores={fusedDmgA=9}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 9 add
attribute @s[scores={fusedDmgA=8}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 8 add
attribute @s[scores={fusedDmgA=7}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 7 add
attribute @s[scores={fusedDmgA=6}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 6 add
attribute @s[scores={fusedDmgA=5}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 5 add
attribute @s[scores={fusedDmgA=4}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 4 add
attribute @s[scores={fusedDmgA=3}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 3 add
attribute @s[scores={fusedDmgA=2}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 2 add
attribute @s[scores={fusedDmgA=1}] minecraft:generic.armor modifier add 0-0-0-0-0 fusedArmor25 1 add