tellraw @s [{"text":"A ","color":"white"},{"text":"catalyst","color":"green"},{"text":" can be applied to an item with a maximum-level enchantments to increase the enchantment further.","color":"white"}]
tellraw @s [{"text":"Doing so will ","color":"white"},{"text":"Soulbind","color":"green"},{"text":" it to you, preventing other players from attacking, using items, or breaking blocks, and giving them blindness and glowing, if they equip it.","color":"white"}]
tellraw @s [{"text":"! You will suffer the same effects if you try to use your ","color":"red"},{"text":"soulbound","color":"green"},{"text":" items while playing as an origin other than Fused! !","color":"red"}]
tellraw @s [{"text":"Soulbinding","color":"green"},{"text":" requires and consumes 15 experience levels.","color":"white"}]
tellraw @s ""
tellraw @s[tag=!fusedAscended] [{"text":"Consuming a ","color":"white"},{"text":"Nether Star ","color":"yellow"},{"text":"and 50 experience levels will permanently remove the experience costs from ","color":"white"},{"text":"Transmutation ","color":"green"},{"text":"and ","color":"white"},{"text":"Ethereal Form","color":"green"},{"text":"'s duration increase and cooldown reduction abilities.","color":"white"}]
tellraw @s[tag=fusedAscended] [{"text":"You have consumed a ","color":"green"},{"text":"Nether Star","color":"yellow"},{"text":", removing experience costs from Transmutation and Ethereal Form's duration increase and cooldown reduction abilities.","color":"green"}]
tellraw @s ""
tellraw @s [{"text":"Single-level enchantments, protection enchantments, the ","color":"white"},{"text":"Thorns ","color":"light_purple"},{"text":"enchantment, and modded enchantments cannot be increased with ","color":"white"},{"text":"catalysts","color":"green"},{"text":".","color":"white"}]
tellraw @s [{"text":"Applying a ","color":"white"},{"text":"catalyst","color":"green"},{"text":" to an item will also give it ","color":"white"},{"text":"Mending","color":"light_purple"},{"text":". You cannot apply more than two ","color":"white"},{"text":"catalysts","color":"green"},{"text":" to an item.","color":"white"}]
tellraw @s ""
tellraw @s [{"text":"Different ","color":"white","bold":false},{"text":"catalysts","color":"green","bold":false},{"text":" affect different enchantments:","color":"white"}]
tellraw @s [{"text":"Chorus Flower","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Unbreaking","color":"light_purple","bold":false}]
tellraw @s [{"text":"Gilded Blackstone","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Sharpness","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Smite","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Impaling","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Frost Walker","color":"light_purple","bold":false},{"text":", and ","color":"white","bold":false},{"text":"Depth Strider","color":"light_purple","bold":false}]
tellraw @s [{"text":"Scute","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Power","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Looting","color":"light_purple","bold":false},{"text":", and ","color":"white","bold":false},{"text":"Respiration","color":"light_purple","bold":false}]
tellraw @s [{"text":"Nautilus Shell","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Efficiency","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Punch","color":"light_purple","bold":false},{"text":", and ","color":"white","bold":false},{"text":"Sweeping Edge","color":"light_purple","bold":false}]
tellraw @s [{"text":"Honey Block","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Piercing","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Fortune","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Knockback","color":"light_purple","bold":false},{"text":", and ","color":"white","bold":false},{"text":"Feather Falling","color":"light_purple","bold":false}]
tellraw @s [{"text":"Dragon's Breath","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Riptide","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Loyalty","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Quick Charge","color":"light_purple","bold":false},{"text":", ","color":"white","bold":false},{"text":"Fire Aspect","color":"light_purple","bold":false},{"text":", and ","color":"white","bold":false},{"text":"Soul Speed","color":"light_purple","bold":false}]
tellraw @s [{"text":"Poisonous Potato","color":"yellow","bold":true},{"text":": Can increase ","color":"white","bold":false},{"text":"Bane of Arthropods","color":"light_purple","bold":false}]
scoreboard players set @s catalysts 0
scoreboard players enable @s catalysts