attribute @s[scores={fusedDmgA=15..}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 15 add
attribute @s[scores={fusedDmgA=14}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 14 add
attribute @s[scores={fusedDmgA=13}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 13 add
attribute @s[scores={fusedDmgA=12}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 12 add
attribute @s[scores={fusedDmgA=11}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 11 add
attribute @s[scores={fusedDmgA=10}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 10 add
attribute @s[scores={fusedDmgA=9}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 9 add
attribute @s[scores={fusedDmgA=8}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 8 add
attribute @s[scores={fusedDmgA=7}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 7 add
attribute @s[scores={fusedDmgA=6}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 6 add
attribute @s[scores={fusedDmgA=5}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 5 add
attribute @s[scores={fusedDmgA=4}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 4 add
attribute @s[scores={fusedDmgA=3}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 3 add
attribute @s[scores={fusedDmgA=2}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 2 add
attribute @s[scores={fusedDmgA=1}] minecraft:generic.armor_toughness modifier add 0-0-0-0-1 fusedTougness25 1 add